sudo: false
language: node_js
node_js:
  - "8"
  - "10"

os:
  - linux
  - osx

script: ./bin/travis.sh
env: TASK=test
install: npm install --ignore-scripts

after_success:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]] && [[ $(echo $TRAVIS_NODE_VERSION | cut -d'.' -f1) == "10" ]]; then npm run coverage:ci; fi

matrix:
  include:
    - node_js: "8"
      os: linux
      env: TASK=code-lint
    - node_js: "8"
      os: linux
      env: TASK=commit-lint
    - node_js: "8"
      os: linux
      env: TASK=verify-docs

branches:
  only:
    - master

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi
